#!/usr/bin/env zsh
# -*- mode: sh; sh-indentation: 4; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
#
# Copyright (c) 2019 Sebastian Gniazdowski

emulate -LR zsh -o extended_glob -o warn_create_global -o typeset_silent \
        -o no_short_loops -o rc_quotes -o no_auto_pushd

local orig
if [[ -r ~/.tigrc ]] {
    orig=~/.tigrc
} elif [[ -r ${XDG_CONFIG_HOME:-$HOME/.config}/tig/config ]] {
    orig=${XDG_CONFIG_HOME:-$HOME/.config}/tig/config
}

command rm -f $ZSH_TIG_DIR/tigrc
if [[ -n $orig ]] {
    command cp $orig $ZSH_TIG_DIR/tigrc
}

command cat $ZSH_TIG_DIR/tigrc_extension >>! $ZSH_TIG_DIR/tigrc

(( !$? )) && \
    { print -P "%F{141}Successfully updated the custom tigrc%f"; ((1)); } || \
    print -P "%F{160}There was a problem creating the custom tigrc" \
        "(detected plugin directory: %F{141}${ZSH_TIG_DIR%/.}%F{160})%f"

